exclude: >
        thesis-projects-tostenzel/.ipynb_checkpoints
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    -   id: reorder-python-imports
        types: [python]

-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    -   id: black
        types: [python]
        exclude: >
            (?x)^(
                scrypy/distributions.py|
                scrypy/nataf_transformation.py
            )$


-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: ['--max-line-length=88', '--extend-ignore=C408,D100,D205,D401,D400,E203,E402,E501,N803,N806,N816,T001,RST299'
        ]
        types: [python]
        additional_dependencies: [
            flake8-bugbear, flake8-builtins, flake8-comprehensions, flake8-docstrings,
            flake8-eradicate, flake8-print, flake8-rst-docstrings, flake8-todo,
            pep8-naming,
        ]
        files: '.*'  # We start with a subfolder and extend the scope later.
        exclude: >
            (?x)^(
                utils/travis_runner.py|
                scrypy/tests/resources/test_transform_distributions/distributions.py|
                scrypy/tests/resources/test_transform_distributions/nataf_transformation.py
            )$