"""Tests elementary_effects.py"""
import sys

# Define parent folder as relative path.
sys.path.append("python")

import numpy as np

from numpy.testing import assert_array_equal

from sampling_schemes import morris_trajectory
from transform_traj_elementary_effects import trans_ee_uncorr_trajectories


def test_trans_ee_uncorr_trajectories():
    """
    Intregation test for `trans_ee_uncorr_trajectories`

    Notes
    -----
    -This test provides strong evidence that the whole transformation
    of the trajectories for the uncorrelated Elementary Effects is correct.
    As written in [1], page 34: The elements in vectors T(p_{i}, i) and
    T(p_{i+1}, i) are the same except of the ith element. This means that -
    without the first row in `trans_pi_i` and the last row in `trans_pi_i` -
    only the diagonal elements of the two trajectories generated by
    `trans_ee_uncorr_trajectories` are different. This is because in T(p_{i}, i)
    to these elements the step is added before the correlation transformation.
    -`ee_corr_trajectories`, however, is hard to test because there, all elements
    differ if there are correlations.

    See Also
    --------
    `trans_ee_uncorr_trajectories`.

    References
    ----------
    [1] Ge, Q. and M. Menendez (2017). Extending morris method for qualitative global
    sensitivityanalysis of models with dependent inputs. Reliability Engineering &
    System Safety 100 (162), 28–39.

    """
    mu = np.array([10, 11, 12, 13, 14])

    cov = np.array(
        [
            [10, 0, 0, 2, 0.5],
            [0, 20, 0.4, 0.15, 0],
            [0, 0.4, 30, 0.05, 0],
            [2, 0.15, 0.05, 40, 0],
            [0.5, 0, 0, 0, 50],
        ]
    )

    n_inputs = 5
    n_levels = 10
    n_traj_sample = 10
    sample_traj_list = list()
    for traj in range(0, n_traj_sample):
        seed = 123 + traj

        m_traj, _ = morris_trajectory(n_inputs, n_levels, seed=seed)
        sample_traj_list.append(m_traj)

    trans_one, trans_zero, _ = trans_ee_uncorr_trajectories(sample_traj_list, cov, mu)

    for traj in range(0, len(trans_zero)):
        for row in range(0, np.size(trans_zero[0], 0) - 1):
            zero = np.delete(trans_zero[traj][row, :], row)
            one = np.delete(trans_one[traj][row + 1, :], row)
            assert_array_equal(zero, one)
